---
- name: Deploy nextcloud cron script
  template:
    src: "nextcloud-anoniplogs.cron.j2"
    dest: "/etc/cron.d/nextcloud-anoniplogs"
    mode: "0640"
  when: nextcloud_log_anonymize_ips

- name: Remove nextcloud cron script
  file:
    state: absent
    path: "/etc/cron.d/nextcloud-anoniplogs"
  when: not nextcloud_log_anonymize_ips

