---
- name: "[ENV] - load environment for ldap"
  include_vars: ldap.yml

# Check nextcloud ldap config exists
- name: Check nextcloud ldap config exists
  shell: |
    docker exec --user www-data nextcloud php occ ldap:show-config s01
  register: nextcloud_ldap_config_exists
  changed_when: False

# Create nextcloud ldap config
- name: Create nextcloud ldap config
  shell: |
    docker exec --user www-data nextcloud php occ ldap:create-empty-config
  when:
    - "nextcloud_ldap_config_exists.stdout"
    - "'Invalid configID' in nextcloud_ldap_config_exists.stdout"

# Set nextcloud ldap config variables
- name: Set nextcloud ldap config variables
  shell: |
    docker exec --user www-data nextcloud php occ ldap:set-config \
    s01 {{ item.key }} "{{ item.value }}"
  with_items: "{{ lookup('dict', nextcloud_ldap_config) }}"

# Test nextcloud ldap config
- name: Test nextcloud ldap config
  shell: |
    docker exec --user www-data nextcloud php occ ldap:test-config s01
  register: nextcloud_ldap_config_test
  changed_when: False
  failed_when:
    - "'configuration is valid' not in nextcloud_ldap_config_test.stdout"
    - "'connection could be established' not in nextcloud_ldap_config_test.stdout"
